### ISSUE TITLE
解决清空输入框后无法输入

### ISSUE THREAD

**Issue by yuuki410** [ZeeXoc/AntiMemetix#1]
为`.edit-area`类增加一个CSS样式：
```css
.edit-area{
    min-height:90%; /* 根据需要修改，也可以是100vh, 100px等等 */
}
```
